// Copyright (c) Lonely Quasar.
// Licensed under the MIT license.

#include "pch.h"
#include "AxanShellIntegration.h"
#include "AxanLog.h"

#include <filesystem>
#include <fstream>
#include <iterator>
#include <vector>

#include <winrt/Windows.Storage.h>

namespace
{
    // ----- the emitted integration scripts (single source of truth) -------------------
    //
    // Materialized verbatim into LocalState; ASCII only. The pwsh script is dot-sourced
    // after the user's profile and wraps the active prompt; the bash wrapper is loaded via
    // --rcfile and installs a PROMPT_COMMAND. Both emit OSC 9;9;"<cwd>" ST each prompt,
    // which WT's SetWorkingDirectory (adaptDispatch.cpp) turns into ICoreState's
    // CurrentWorkingDirectory — the value M5's label engine reads.

    constexpr std::string_view _kPwshScript = R"PS(# axan PowerShell shell integration (milestone M10) - regenerated by axan; do not edit.
# Dot-sourced after the user's $PROFILE via: <pwsh> -NoExit -Command ". '<this file>'".
# Wraps the active prompt to emit each prompt:
#   OSC 9;9;"<cwd>" ST  - working directory (ConEmu/WT convention; feeds axan's M5 labels)
#   OSC 133;A      ST   - FinalTerm prompt-start mark (free; lets WT draw prompt marks)
# It chains whatever prompt was in effect when this loaded, so the user's prompt stays.

if (-not (Test-Path variable:global:__axanOriginalPrompt)) {
    $global:__axanOriginalPrompt = $function:prompt
}

function global:prompt {
    $esc = [char]27
    try { $cwd = $PWD.ProviderPath } catch { $cwd = '' }
    $seq = ''
    if ($cwd) { $seq += "$esc]9;9;`"$cwd`"$esc\" }
    $seq += "$esc]133;A$esc\"
    $seq + (& $global:__axanOriginalPrompt)
}
)PS";

    constexpr std::string_view _kBashRcfile = R"SH(# axan bash/WSL shell-integration wrapper (milestone M10) - regenerated by axan; do not edit.
# Loaded via: wsl ... -- bash --rcfile <this> -i
# --rcfile suppresses the normal ~/.bashrc read, so re-source it first, then install a
# PROMPT_COMMAND that emits OSC 9;9;"<cwd>" each prompt. Unlike the Linux build this does
# NOT rely on VTE's /etc/profile.d hooks (absent in a headless WSL distro) - it emits the
# sequence directly. `wslpath -w` reports a \\wsl.localhost path when available so axan's
# $branch/$repo (a Windows-side git walk) resolve; otherwise the raw cwd is sent.

if [ -r "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

__axan_emit_osc99() {
    local p
    if command -v wslpath >/dev/null 2>&1; then
        p="$(wslpath -w "$PWD" 2>/dev/null)" || p="$PWD"
    else
        p="$PWD"
    fi
    printf '\033]9;9;"%s"\033\\' "$p"
}

case ":$PROMPT_COMMAND:" in
    *__axan_emit_osc99*) ;;
    ::) PROMPT_COMMAND="__axan_emit_osc99" ;;
    *)  PROMPT_COMMAND="__axan_emit_osc99; $PROMPT_COMMAND" ;;
esac
)SH";

    // ----- small parsing helpers ------------------------------------------------------

    // The basename of a commandline's first token (the exe), lowercased. Mirrors M5's
    // _shellBasenameFromCommandline: handles a quoted exe ("C:\with space\pwsh.exe" -arg)
    // and a bare first token. Returns "" when there's nothing usable.
    std::wstring _exeBasenameLower(std::wstring_view cmdline)
    {
        while (!cmdline.empty() && (cmdline.front() == L' ' || cmdline.front() == L'\t'))
        {
            cmdline.remove_prefix(1);
        }
        if (cmdline.empty())
        {
            return {};
        }
        std::wstring_view exe;
        if (cmdline.front() == L'"')
        {
            const auto close = cmdline.find(L'"', 1);
            exe = cmdline.substr(1, close == std::wstring_view::npos ? std::wstring_view::npos : close - 1);
        }
        else
        {
            const auto space = cmdline.find_first_of(L" \t");
            exe = cmdline.substr(0, space);
        }
        if (exe.empty())
        {
            return {};
        }
        auto name = std::filesystem::path{ exe }.filename().wstring();
        for (auto& c : name)
        {
            if (c >= L'A' && c <= L'Z')
            {
                c = static_cast<wchar_t>(c - L'A' + L'a');
            }
        }
        return name;
    }

    // Tokenize the *arguments* (everything after the exe), lowercased, honoring double
    // quotes. Good enough for flag-presence gates: profile commandlines are simple, and a
    // run-defining flag (-Command, /c, --) is never itself quoted.
    std::vector<std::wstring> _argTokensLower(std::wstring_view cmdline)
    {
        size_t i = 0;
        const auto skipws = [&]() {
            while (i < cmdline.size() && (cmdline[i] == L' ' || cmdline[i] == L'\t'))
            {
                ++i;
            }
        };

        // Skip the first token (the exe), honoring a quoted path.
        skipws();
        if (i < cmdline.size() && cmdline[i] == L'"')
        {
            ++i;
            while (i < cmdline.size() && cmdline[i] != L'"')
            {
                ++i;
            }
            if (i < cmdline.size())
            {
                ++i;
            }
        }
        else
        {
            while (i < cmdline.size() && cmdline[i] != L' ' && cmdline[i] != L'\t')
            {
                ++i;
            }
        }

        std::vector<std::wstring> tokens;
        while (true)
        {
            skipws();
            if (i >= cmdline.size())
            {
                break;
            }
            std::wstring tok;
            if (cmdline[i] == L'"')
            {
                ++i;
                while (i < cmdline.size() && cmdline[i] != L'"')
                {
                    tok += cmdline[i++];
                }
                if (i < cmdline.size())
                {
                    ++i;
                }
            }
            else
            {
                while (i < cmdline.size() && cmdline[i] != L' ' && cmdline[i] != L'\t')
                {
                    tok += cmdline[i++];
                }
            }
            for (auto& c : tok)
            {
                if (c >= L'A' && c <= L'Z')
                {
                    c = static_cast<wchar_t>(c - L'A' + L'a');
                }
            }
            tokens.push_back(std::move(tok));
        }
        return tokens;
    }

    bool _hasToken(const std::vector<std::wstring>& tokens, std::wstring_view target)
    {
        for (const auto& t : tokens)
        {
            if (t == target)
            {
                return true;
            }
        }
        return false;
    }

    // PowerShell run-defining flags: if any is present the spawn is a custom one-shot/script,
    // so we leave it alone rather than colliding with the user's own -Command/-File.
    //
    // PowerShell accepts any unambiguous prefix of a parameter name (-com == -Command) and a
    // colon-attached value (-Command:"x"); both must hit this gate or our injected
    // "-NoExit -Command" collides with the user's and the spawn breaks (#436 item 9). So a
    // token counts when it starts with '-' and its stem — the part before an optional ':' —
    // is any prefix of "command", "encodedcommand", or "file" (plus "ec", pwsh's documented
    // EncodedCommand alias, which is not a strict prefix). Deliberately looser than
    // PowerShell's real ambiguity rule: a false positive merely skips the prompt-marker
    // injection (safe); a false negative double-injects and the shell fails to launch.
    // Tokens arrive lowercased from _tokenize, so plain comparisons are case-insensitive.
    bool _powershellHasRunFlag(const std::vector<std::wstring>& tokens)
    {
        static constexpr std::wstring_view runParams[] = { L"command", L"encodedcommand", L"file" };
        for (const auto& t : tokens)
        {
            if (t.size() < 2 || t[0] != L'-')
            {
                continue;
            }
            auto stem = std::wstring_view{ t }.substr(1);
            if (const auto colon = stem.find(L':'); colon != std::wstring_view::npos)
            {
                stem = stem.substr(0, colon);
            }
            if (stem.empty())
            {
                continue; // a bare "-:" or "-" defines nothing
            }
            if (stem == L"ec")
            {
                return true;
            }
            for (const auto full : runParams)
            {
                if (stem.size() <= full.size() && full.compare(0, stem.size(), stem) == 0)
                {
                    return true;
                }
            }
        }
        return false;
    }

    // WSL one-shot: `--` (a command follows), or -e/--exec (run a single program). In those
    // cases there is no interactive prompt to hook, so skip.
    bool _wslHasOneShot(const std::vector<std::wstring>& tokens)
    {
        return _hasToken(tokens, L"--") || _hasToken(tokens, L"-e") || _hasToken(tokens, L"--exec");
    }

    // Escape a path for embedding inside a PowerShell single-quoted string ('...'): double
    // any embedded single quote. Covers the rare apostrophe-in-username LocalState path.
    std::wstring _psSingleQuoteEscape(const std::wstring& s)
    {
        std::wstring out;
        out.reserve(s.size() + 2);
        for (const auto c : s)
        {
            out += c;
            if (c == L'\'')
            {
                out += L'\'';
            }
        }
        return out;
    }

    // Translate a Windows path to the WSL automount form: C:\a\b -> /mnt/c/a/b (default
    // /mnt prefix). Used to point `bash --rcfile` at the LocalState wrapper from inside WSL.
    std::wstring _toWslMntPath(const std::filesystem::path& winPath)
    {
        const auto s = winPath.wstring();
        if (s.size() >= 2 && s[1] == L':')
        {
            auto drive = s[0];
            if (drive >= L'A' && drive <= L'Z')
            {
                drive = static_cast<wchar_t>(drive - L'A' + L'a');
            }
            std::wstring out = L"/mnt/";
            out += drive;
            for (size_t i = 2; i < s.size(); ++i)
            {
                out += (s[i] == L'\\') ? L'/' : s[i];
            }
            return out;
        }
        return s;
    }

    // ----- LocalState materialization -------------------------------------------------

    // LocalState\shell-integration — beside settings.json/state.json. ApplicationData throws
    // for an unpackaged process, so callers guard the whole computation.
    std::filesystem::path _shellIntegrationDir()
    {
        const auto localFolder = winrt::Windows::Storage::ApplicationData::Current().LocalFolder();
        return std::filesystem::path{ localFolder.Path().c_str() } / L"shell-integration";
    }

    // Write `body` to `path` if the file is missing or its content differs (idempotent;
    // safe to call on every spawn). Returns true if the file is present and up to date.
    bool _materialize(const std::filesystem::path& path, std::string_view body)
    {
        std::error_code ec;
        std::filesystem::create_directories(path.parent_path(), ec);

        {
            std::ifstream in{ path, std::ios::binary };
            if (in)
            {
                const std::string existing{ std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>() };
                if (existing.size() == body.size() && std::string_view{ existing } == body)
                {
                    return true; // already current
                }
            }
        }

        std::ofstream out{ path, std::ios::binary | std::ios::trunc };
        if (!out)
        {
            return false;
        }
        out.write(body.data(), static_cast<std::streamsize>(body.size()));
        return out.good();
    }
}

namespace Axan
{
    ShellFamily DetectShellFamily(std::wstring_view commandline)
    {
        const auto exe = _exeBasenameLower(commandline);
        if (exe == L"pwsh.exe" || exe == L"powershell.exe")
        {
            return ShellFamily::PowerShell;
        }
        if (exe == L"cmd.exe")
        {
            return ShellFamily::Cmd;
        }
        if (exe == L"wsl.exe")
        {
            return ShellFamily::Wsl;
        }
        return ShellFamily::Unknown;
    }

    ShellIntegration ComputeShellIntegration(std::wstring_view commandline, bool enabled)
    {
        ShellIntegration result;
        result.commandline.assign(commandline);
        if (!enabled)
        {
            return result;
        }

        const auto family = DetectShellFamily(commandline);
        const auto familyName = family == ShellFamily::PowerShell ? "powershell" :
                                family == ShellFamily::Cmd        ? "cmd" :
                                family == ShellFamily::Wsl        ? "wsl" :
                                                                    "unknown";
        Axan::Log::Info("AxanShellIntegration", "ComputeShellIntegration: spawn seam", { { "shell", familyName } });
        if (family == ShellFamily::Unknown)
        {
            return result;
        }

        const auto tokens = _argTokensLower(commandline);

        try
        {
            switch (family)
            {
            case ShellFamily::PowerShell:
            {
                // A custom -Command/-File/-EncodedCommand spawn owns its own behavior; don't
                // collide with it.
                if (_powershellHasRunFlag(tokens))
                {
                    return result;
                }
                const auto script = _shellIntegrationDir() / L"pwsh" / L"axan-shell-integration.ps1";
                if (!_materialize(script, _kPwshScript))
                {
                    return result;
                }

                std::wstring cl{ commandline };
                if (!_hasToken(tokens, L"-noexit"))
                {
                    cl += L" -NoExit";
                }
                cl += L" -Command \". '";
                cl += _psSingleQuoteEscape(script.wstring());
                cl += L"'\"";
                result.commandline = std::move(cl);
                result.applied = true;
                return result;
            }

            case ShellFamily::Cmd:
            {
                // A `/c` one-shot has no interactive prompt to hook. (`/k` is fine: it stays
                // interactive, and the env-based %PROMPT% co-exists with it — best effort.)
                if (_hasToken(tokens, L"/c"))
                {
                    return result;
                }
                // %PROMPT% codes: $E=ESC, $P=cwd, $G='>'. Emit OSC 9;9;"<cwd>" ST, then the
                // conventional "<cwd>>" prompt. cmd re-expands $P each prompt, so cwd tracks.
                result.promptEnv = std::wstring{ L"$E]9;9;\"$P\"$E\\$P$G" };
                result.applied = true;
                return result;
            }

            case ShellFamily::Wsl:
            {
                if (_wslHasOneShot(tokens))
                {
                    return result;
                }
                const auto script = _shellIntegrationDir() / L"bash" / L"axan-rcfile.sh";
                if (!_materialize(script, _kBashRcfile))
                {
                    return result;
                }

                std::wstring cl{ commandline };
                cl += L" -- bash --rcfile \"";
                cl += _toWslMntPath(script);
                cl += L"\" -i";
                result.commandline = std::move(cl);
                result.applied = true;
                return result;
            }

            default:
                return result;
            }
        }
        catch (...)
        {
            // ApplicationData unavailable (unpackaged) or any IO failure: fall back to the
            // unmodified spawn. Shell integration is a nicety, never load-bearing for spawn.
            Axan::Log::Warn("AxanShellIntegration", "ComputeShellIntegration: materialize/IO failed; spawning unmodified", { { "shell", familyName } });
            result.commandline.assign(commandline);
            result.applied = false;
            result.promptEnv.reset();
            return result;
        }
    }
}
